apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-deployment
  labels:
      app: rng
spec:
  replicas: 1
  selector:
      matchLabels:
          app: rng
  template:
    metadata:
        labels:
            app: rng
    spec:
      containers:
        - name: rng
          image: public.ecr.aws/v6d1g4q0/spring-boot-image-container:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8085
            name: http
            protocol: TCP
